In [1]:
!pip install numpy


In [14]:

!pip list

Package                                  Version
---------------------------------------- ------------------
absl-py                                  1.4.0
accelerate                               1.12.0
access                                   1.1.10.post3
affine                                   2.4.0
aiofiles                                 24.1.0
aiohappyeyeballs                         2.6.1
aiohttp                                  3.13.3
aiosignal                                1.4.0
aiosqlite                                0.22.1
alabaster                                1.0.0
albucore                                 0.0.24
albumentations                           2.0.8
ale-py                                   0.11.2
alembic                                  1.17.2
altair                                   5.5.0
annotated-doc                            0.0.4
annotated-types                          0.7.0
antlr4-python3-runtime                   4.9.3
anyio                          

In [4]:
import numpy as np
print(np.__version__)


2.0.2


In [5]:
import openai

In [6]:
import pandas as pd

In [8]:
lista=[1,2,3]
lista1=[]
for i in lista:
   lista1.append(i*2)

print(lista1)

[2, 4, 6]


In [62]:

import time

start_time = time.time()  # Marca el tiempo de inicio

lista = [1, 2, 3]
lista1 = []
for i in lista:
   lista1.append(i * 2)

print(lista1)

end_time = time.time()    # Marca el tiempo de finalización

elapsed_time = end_time - start_time
print(f"Tiempo de ejecución: {elapsed_time} segundos")


[2, 4, 6]
Tiempo de ejecución: 0.00033092498779296875 segundos


medimos el tiempo de ejecucion y se ve que

In [63]:
start_time = time.time()
lista = [1, 2, 3]
arreglo=np.array(lista)
arreglo1=arreglo*2
print(arreglo1)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"Tiempo de ejecución: {elapsed_time} segundos")

[2 4 6]
Tiempo de ejecución: 0.0004703998565673828 segundos


In [13]:
import numpy as np
arreglo=np.array(lista)
arreglo1=arreglo*2
print(arreglo1)
a=list(arreglo1)
print(a)
type(a)

[2 4 6]
[np.int64(2), np.int64(4), np.int64(6)]


list

In [16]:
print(arreglo)
print(arreglo1)

[1 2 3]
[2 4 6]


In [46]:

producto_punto = np.dot(arreglo, arreglo1)
print(f"El producto punto de arreglo y arreglo1 es: {producto_punto}")


El producto punto de arreglo y arreglo1 es: 28


In [20]:
matriz=np.array([[1,2,3],[4,5,6]])
print(matriz)

[[1 2 3]
 [4 5 6]]


In [25]:
valor_5=matriz[1,1]
print(valor_5)

5


In [28]:
matriz-2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [40]:
arr=np.arange(1,5)
print(arr)
print(arr.shape)

[1 2 3 4]
(4,)


In [38]:
matriz_aleatoria=np.random.rand(2,3)
print(matriz_aleatoria)

[[0.32288097 0.98361775 0.02293993]
 [0.63235682 0.98617967 0.41795653]]


In [44]:
np.diag(matriz_aleatoria)

array([0.32288097, 0.98617967])

In [42]:
np.mean(matriz_aleatoria)

np.float64(0.560988611663659)

In [43]:
np.std(matriz_aleatoria)

np.float64(0.3490811895217862)

In [41]:
arr=np.arange(1,5)
r=arr.reshape(2,2)
print(r)
print(r.shape)

[[1 2]
 [3 4]]
(2, 2)


In [48]:
matriz_aleatoria

array([[0.32288097, 0.98361775, 0.02293993],
       [0.63235682, 0.98617967, 0.41795653]])

In [47]:

matriz_transpuesta = matriz_aleatoria.T
print(matriz_transpuesta)

[[0.32288097 0.63235682]
 [0.98361775 0.98617967]
 [0.02293993 0.41795653]]
